#![no_std]
#![no_main]

extern crate alloc;
use alloc::string::ToString;

use libd::{
    println,
    syscall::{execve, exit, fork, system_shutdown, wait, yield_},
};

// #[no_mangle]
// fn main() -> i32 {
//     run_tests();
//     println!("TESTS FINISH");
//     system_shutdown();
// }

// this can pass once
const TESTCASES: [&str; 15] = [
    "./iozone_testcode.sh",
    "./libc-bench",
    "./lmbench_testcode.sh",
    "./time-test",
    "./unixbench_testcode.sh",
    "./netperf_testcode.sh",
    "./iperf_testcode.sh",
    "./lua_testcode.sh",
    "./busybox_testcode.sh",
    // "./libctest_testcode.sh",
    "./splice-test-1",
    "./splice-test-2",
    "./splice-test-3",
    "./splice-test-4",
    "./splice-test-5",
    "./cyclictest_testcode.sh",
    // "./test-ltp.sh ltp/testcases/bin/access01",
    // "./test-ltp.sh ltp/testcases/bin/access02",
    // "./test-ltp.sh ltp/testcases/bin/access03",
    // "./test-ltp.sh ltp/testcases/bin/access04",
    // "./test-ltp.sh ltp/testcases/bin/acct01",
    // "./test-ltp.sh ltp/testcases/bin/acct02",
    // "./test-ltp.sh ltp/testcases/bin/add_key01",
    // "./test-ltp.sh ltp/testcases/bin/add_key02",
    // "./test-ltp.sh ltp/testcases/bin/add_key03",
    // "./test-ltp.sh ltp/testcases/bin/add_key04",
    // "./test-ltp.sh ltp/testcases/bin/add_key05",
    // "./test-ltp.sh ltp/testcases/bin/adjtimex01",
    // "./test-ltp.sh ltp/testcases/bin/arch_prctl01",
    // "./test-ltp.sh ltp/testcases/bin/bpf_prog01",
    // "./test-ltp.sh ltp/testcases/bin/bpf_prog02",
    // "./test-ltp.sh ltp/testcases/bin/bpf_prog03",
    // "./test-ltp.sh ltp/testcases/bin/bpf_prog04",
    // "./test-ltp.sh ltp/testcases/bin/bpf_prog05",
    // "./test-ltp.sh ltp/testcases/bin/bpf_prog06",
    // "./test-ltp.sh ltp/testcases/bin/bpf_prog07",
    // "./test-ltp.sh ltp/testcases/bin/capget01",
    // "./test-ltp.sh ltp/testcases/bin/capget02",
    // "./test-ltp.sh ltp/testcases/bin/capset01",
    // "./test-ltp.sh ltp/testcases/bin/capset02",
    // "./test-ltp.sh ltp/testcases/bin/capset03",
    // "./test-ltp.sh ltp/testcases/bin/capset04",
    // "./test-ltp.sh ltp/testcases/bin/cacheflush01",
    // "./test-ltp.sh ltp/testcases/bin/chown01",
    // "./test-ltp.sh ltp/testcases/bin/chown01_16",
    // "./test-ltp.sh ltp/testcases/bin/chown02",
    // "./test-ltp.sh ltp/testcases/bin/chown02_16",
    // "./test-ltp.sh ltp/testcases/bin/chown03",
    // "./test-ltp.sh ltp/testcases/bin/chown03_16",
    // "./test-ltp.sh ltp/testcases/bin/chown04",
    // "./test-ltp.sh ltp/testcases/bin/chown04_16",
    // "./test-ltp.sh ltp/testcases/bin/chown05",
    // "./test-ltp.sh ltp/testcases/bin/chown05_16",
    // "./test-ltp.sh ltp/testcases/bin/clock_adjtime01",
    // "./test-ltp.sh ltp/testcases/bin/clock_adjtime02",
    // "./test-ltp.sh ltp/testcases/bin/close_range01",
    // "./test-ltp.sh ltp/testcases/bin/close_range02",
    // "./test-ltp.sh ltp/testcases/bin/close_range02",
    // "./test-ltp.sh ltp/testcases/bin/delete_module01",
    // "./test-ltp.sh ltp/testcases/bin/delete_module02",
    // "./test-ltp.sh ltp/testcases/bin/delete_module03",
    // "./test-ltp.sh ltp/testcases/bin/epoll_create01",
    // "./test-ltp.sh ltp/testcases/bin/epoll_create02",
    // "./test-ltp.sh ltp/testcases/bin/epoll_create1_01",
    // "./test-ltp.sh ltp/testcases/bin/epoll_create1_02",
    // "./test-ltp.sh ltp/testcases/bin/epoll_ctl01",
    // "./test-ltp.sh ltp/testcases/bin/epoll_ctl02",
    // "./test-ltp.sh ltp/testcases/bin/epoll_ctl03",
    // "./test-ltp.sh ltp/testcases/bin/epoll_ctl04",
    // "./test-ltp.sh ltp/testcases/bin/epoll_ctl05",
    // "./test-ltp.sh ltp/testcases/bin/epoll_wait01",
    // "./test-ltp.sh ltp/testcases/bin/epoll_wait02",
    // "./test-ltp.sh ltp/testcases/bin/epoll_wait03",
    // "./test-ltp.sh ltp/testcases/bin/epoll_wait04",
    // "./test-ltp.sh ltp/testcases/bin/epoll_wait05",
    // "./test-ltp.sh ltp/testcases/bin/epoll_wait06",
    // "./test-ltp.sh ltp/testcases/bin/epoll_wait07",
    // "./test-ltp.sh ltp/testcases/bin/epoll_pwait01",
    // "./test-ltp.sh ltp/testcases/bin/epoll_pwait02",
    // "./test-ltp.sh ltp/testcases/bin/epoll_pwait03",
    // "./test-ltp.sh ltp/testcases/bin/epoll_pwait04",
    // "./test-ltp.sh ltp/testcases/bin/epoll_pwait05",
    // "./test-ltp.sh ltp/testcases/bin/eventfd01",
    // "./test-ltp.sh ltp/testcases/bin/eventfd02",
    // "./test-ltp.sh ltp/testcases/bin/eventfd03",
    // "./test-ltp.sh ltp/testcases/bin/eventfd04",
    // "./test-ltp.sh ltp/testcases/bin/eventfd05",
    // "./test-ltp.sh ltp/testcases/bin/eventfd06",
    // "./test-ltp.sh ltp/testcases/bin/eventfd2_01",
    // "./test-ltp.sh ltp/testcases/bin/eventfd2_02",
    // "./test-ltp.sh ltp/testcases/bin/eventfd2_03",
    // "./test-ltp.sh ltp/testcases/bin/execl01",
    // "./test-ltp.sh ltp/testcases/bin/execle01",
    // "./test-ltp.sh ltp/testcases/bin/execlp01",
    // "./test-ltp.sh ltp/testcases/bin/execv01",
    // "./test-ltp.sh ltp/testcases/bin/execve01",
    // "./test-ltp.sh ltp/testcases/bin/execve02",
    // "./test-ltp.sh ltp/testcases/bin/execve03",
    // "./test-ltp.sh ltp/testcases/bin/execve04",
    // "./test-ltp.sh ltp/testcases/bin/execve05",
    // "./test-ltp.sh ltp/testcases/bin/execve06",
    // "./test-ltp.sh ltp/testcases/bin/execvp01",
    // "./test-ltp.sh ltp/testcases/bin/execveat01",
    // "./test-ltp.sh ltp/testcases/bin/execveat02",
    // "./test-ltp.sh ltp/testcases/bin/execveat03",
    // "./test-ltp.sh ltp/testcases/bin/exit_group01",
    // "./test-ltp.sh ltp/testcases/bin/faccessat01",
    // "./test-ltp.sh ltp/testcases/bin/faccessat02",
    // "./test-ltp.sh ltp/testcases/bin/faccessat201",
    // "./test-ltp.sh ltp/testcases/bin/faccessat202",
    // "./test-ltp.sh ltp/testcases/bin/fallocate01",
    // "./test-ltp.sh ltp/testcases/bin/fallocate02",
    // "./test-ltp.sh ltp/testcases/bin/fallocate03",
    // "./test-ltp.sh ltp/testcases/bin/fallocate04",
    // "./test-ltp.sh ltp/testcases/bin/fallocate05",
    // "./test-ltp.sh ltp/testcases/bin/fallocate06",
    // "./test-ltp.sh ltp/testcases/bin/fsetxattr01",
    // "./test-ltp.sh ltp/testcases/bin/fsetxattr02",
    // "./test-ltp.sh ltp/testcases/bin/posix_fadvise01",
    // "./test-ltp.sh ltp/testcases/bin/posix_fadvise01_64",
    // "./test-ltp.sh ltp/testcases/bin/posix_fadvise02",
    // "./test-ltp.sh ltp/testcases/bin/posix_fadvise02_64",
    // "./test-ltp.sh ltp/testcases/bin/posix_fadvise03",
    // "./test-ltp.sh ltp/testcases/bin/posix_fadvise03_64",
    // "./test-ltp.sh ltp/testcases/bin/posix_fadvise04",
    // "./test-ltp.sh ltp/testcases/bin/posix_fadvise04_64",
    // "./test-ltp.sh ltp/testcases/bin/fchmod01",
    // "./test-ltp.sh ltp/testcases/bin/fchmod02",
    // "./test-ltp.sh ltp/testcases/bin/fchmod03",
    // "./test-ltp.sh ltp/testcases/bin/fchmod04",
    // "./test-ltp.sh ltp/testcases/bin/fchmod05",
    // "./test-ltp.sh ltp/testcases/bin/fchmod06",
    // "./test-ltp.sh ltp/testcases/bin/fchmodat01",
    // "./test-ltp.sh ltp/testcases/bin/fchmodat02",
    // "./test-ltp.sh ltp/testcases/bin/fchown01",
    // "./test-ltp.sh ltp/testcases/bin/fchown01_16",
    // "./test-ltp.sh ltp/testcases/bin/fchown02",
    // "./test-ltp.sh ltp/testcases/bin/fchown02_16",
    // "./test-ltp.sh ltp/testcases/bin/fchown03",
    // "./test-ltp.sh ltp/testcases/bin/fchown03_16",
    // "./test-ltp.sh ltp/testcases/bin/fchown04",
    // "./test-ltp.sh ltp/testcases/bin/fchown04_16",
    // "./test-ltp.sh ltp/testcases/bin/fchown05",
    // "./test-ltp.sh ltp/testcases/bin/fchown05_16",
    // "./test-ltp.sh ltp/testcases/bin/fchownat01",
    // "./test-ltp.sh ltp/testcases/bin/fchownat02",
    // "./test-ltp.sh ltp/testcases/bin/fchownat02",
    // "./test-ltp.sh ltp/testcases/bin/fdatasync01",
    // "./test-ltp.sh ltp/testcases/bin/fdatasync02",
    // "./test-ltp.sh ltp/testcases/bin/fdatasync03",
    // "./test-ltp.sh ltp/testcases/bin/fgetxattr01",
    // "./test-ltp.sh ltp/testcases/bin/fgetxattr02",
    // "./test-ltp.sh ltp/testcases/bin/fgetxattr03",
    // "./test-ltp.sh ltp/testcases/bin/finit_module01",
    // "./test-ltp.sh ltp/testcases/bin/finit_module02",
    // "./test-ltp.sh ltp/testcases/bin/flistxattr01",
    // "./test-ltp.sh ltp/testcases/bin/flistxattr02",
    // "./test-ltp.sh ltp/testcases/bin/flistxattr03",
    // "./test-ltp.sh ltp/testcases/bin/fdatasync01",
    // "./test-ltp.sh ltp/testcases/bin/fdatasync02",
    // "./test-ltp.sh ltp/testcases/bin/fdatasync03",
    // "./test-ltp.sh ltp/testcases/bin/fgetxattr01",
    // "./test-ltp.sh ltp/testcases/bin/fgetxattr02",
    // "./test-ltp.sh ltp/testcases/bin/fgetxattr03",
    // "./test-ltp.sh ltp/testcases/bin/finit_module01",
    // "./test-ltp.sh ltp/testcases/bin/finit_module02",
    // "./test-ltp.sh ltp/testcases/bin/flistxattr01",
    // "./test-ltp.sh ltp/testcases/bin/flistxattr02",
    // "./test-ltp.sh ltp/testcases/bin/flistxattr03",
    // "./test-ltp.sh ltp/testcases/bin/flock01",
    // "./test-ltp.sh ltp/testcases/bin/flock02",
    // "./test-ltp.sh ltp/testcases/bin/flock03",
    // "./test-ltp.sh ltp/testcases/bin/flock04",
    // "./test-ltp.sh ltp/testcases/bin/flock06",
    // "./test-ltp.sh ltp/testcases/bin/fmtmsg01",
    // "./test-ltp.sh ltp/testcases/bin/fork01",
    // "./test-ltp.sh ltp/testcases/bin/fork03",
    // "./test-ltp.sh ltp/testcases/bin/fork04",
    // "./test-ltp.sh ltp/testcases/bin/fork05",
    // "./test-ltp.sh ltp/testcases/bin/fork_procs -n 1000",
    // "./test-ltp.sh ltp/testcases/bin/fork07",
    // "./test-ltp.sh ltp/testcases/bin/fork08",
    // "./test-ltp.sh ltp/testcases/bin/fork09",
    // "./test-ltp.sh ltp/testcases/bin/fork10",
    // "./test-ltp.sh ltp/testcases/bin/fork_procs -n 100",
    // "./test-ltp.sh ltp/testcases/bin/fork13",
    // "./test-ltp.sh ltp/testcases/bin/fork14",
    // "./test-ltp.sh ltp/testcases/bin/fpathconf01",
    // "./test-ltp.sh ltp/testcases/bin/fremovexattr01",
    // "./test-ltp.sh ltp/testcases/bin/fremovexattr02",
    // "./test-ltp.sh ltp/testcases/bin/fsconfig01",
    // "./test-ltp.sh ltp/testcases/bin/fsconfig02",
    // "./test-ltp.sh ltp/testcases/bin/fsconfig03",
    // "./test-ltp.sh ltp/testcases/bin/setrlimit01",
    //     "./test-ltp.sh ltp/testcases/bin/setrlimit02",
    //     "./test-ltp.sh ltp/testcases/bin/setpgid01",
    //     "./test-ltp.sh ltp/testcases/bin/setpgid02",
    //     "./test-ltp.sh ltp/testcases/bin/abort01",
    //     "./test-ltp.sh ltp/testcases/bin/accept01",
    //     "./test-ltp.sh ltp/testcases/bin/accept02",
    //     "./test-ltp.sh ltp/testcases/bin/accept03",
    //     "./test-ltp.sh ltp/testcases/bin/brk01",
    //     "./test-ltp.sh ltp/testcases/bin/brk02",
    //     "./test-ltp.sh ltp/testcases/bin/chroot01",
    //     "./test-ltp.sh ltp/testcases/bin/chroot02",
    //     "./test-ltp.sh ltp/testcases/bin/chroot03",
    //     "./test-ltp.sh ltp/testcases/bin/chroot04",
    //     "./test-ltp.sh ltp/testcases/bin/alarm02",
    //     "./test-ltp.sh ltp/testcases/bin/alarm03",
    //     "./test-ltp.sh ltp/testcases/bin/alarm05",
    //     "./test-ltp.sh ltp/testcases/bin/alarm06",
    //     "./test-ltp.sh ltp/testcases/bin/alarm07",
    //     "./test-ltp.sh ltp/testcases/bin/clock_nanosleep01",
    //     "./test-ltp.sh ltp/testcases/bin/clock_nanosleep02",
    //     "./test-ltp.sh ltp/testcases/bin/clock_nanosleep03",
    //     "./test-ltp.sh ltp/testcases/bin/clock_nanosleep04",
    //     "./test-ltp.sh ltp/testcases/bin/clock_gettime01",
    //     "./test-ltp.sh ltp/testcases/bin/clock_gettime02",
    //     "./test-ltp.sh ltp/testcases/bin/clock_gettime03",
    //     "./test-ltp.sh ltp/testcases/bin/clock_gettime04",
    //     "./test-ltp.sh ltp/testcases/bin/clock_settime01",
    //     "./test-ltp.sh ltp/testcases/bin/clock_settime02",
    //     "./test-ltp.sh ltp/testcases/bin/clock_settime03",
    //     "./test-ltp.sh ltp/testcases/bin/bind01",
    //     "./test-ltp.sh ltp/testcases/bin/bind02",
    //     "./test-ltp.sh ltp/testcases/bin/bind03",
    //     "./test-ltp.sh ltp/testcases/bin/bind04",
    //     "./test-ltp.sh ltp/testcases/bin/bind05",
    //     "./test-ltp.sh ltp/testcases/bin/bind06",
    //     "./test-ltp.sh ltp/testcases/bin/clone01",
    //     "./test-ltp.sh ltp/testcases/bin/clone02",
    //     "./test-ltp.sh ltp/testcases/bin/clone03",
    //     "./test-ltp.sh ltp/testcases/bin/clone04",
    //     "./test-ltp.sh ltp/testcases/bin/clone05",
    //     "./test-ltp.sh ltp/testcases/bin/clone06",
    //     "./test-ltp.sh ltp/testcases/bin/clone07",
    //     "./test-ltp.sh ltp/testcases/bin/clone08",
    //     "./test-ltp.sh ltp/testcases/bin/clone09",
    //     "./test-ltp.sh ltp/testcases/bin/clone301",
    //     "./test-ltp.sh ltp/testcases/bin/clone302",
    //     "./test-ltp.sh ltp/testcases/bin/clone303",
    //     "./test-ltp.sh ltp/testcases/bin/close01",
    //     "./test-ltp.sh ltp/testcases/bin/close02",
    //     "./test-ltp.sh ltp/testcases/bin/connect01",
    //     "./test-ltp.sh ltp/testcases/bin/connect02",
    //     "./test-ltp.sh ltp/testcases/bin/creat01",
    //     "./test-ltp.sh ltp/testcases/bin/creat03",
    //     "./test-ltp.sh ltp/testcases/bin/creat04",
    //     "./test-ltp.sh ltp/testcases/bin/creat05",
    //     "./test-ltp.sh ltp/testcases/bin/creat06",
    //     "./test-ltp.sh ltp/testcases/bin/creat07",
    //     "./test-ltp.sh ltp/testcases/bin/creat08",
    //     "./test-ltp.sh ltp/testcases/bin/creat09",
    //     "./test-ltp.sh ltp/testcases/bin/dup01",
    //     "./test-ltp.sh ltp/testcases/bin/dup02",
    //     "./test-ltp.sh ltp/testcases/bin/dup03",
    //     "./test-ltp.sh ltp/testcases/bin/dup04",
    //     "./test-ltp.sh ltp/testcases/bin/dup05",
    //     "./test-ltp.sh ltp/testcases/bin/dup06",
    //     "./test-ltp.sh ltp/testcases/bin/dup07",
    //     "./test-ltp.sh ltp/testcases/bin/dup201",
    //     "./test-ltp.sh ltp/testcases/bin/dup202",
    //     "./test-ltp.sh ltp/testcases/bin/dup204",
    //     "./test-ltp.sh ltp/testcases/bin/dup205",
    //     "./test-ltp.sh ltp/testcases/bin/dup206",
    //     "./test-ltp.sh ltp/testcases/bin/dup207",
    //     "./test-ltp.sh ltp/testcases/bin/dup3_01",
    //     "./test-ltp.sh ltp/testcases/bin/dup3_02",
    //     "./test-ltp.sh ltp/testcases/bin/exit01",
    //     "./test-ltp.sh ltp/testcases/bin/exit02",
    //     "./test-ltp.sh ltp/testcases/bin/chdir01",
    //     "./test-ltp.sh ltp/testcases/bin/chdir04",
    //     "./test-ltp.sh ltp/testcases/bin/fchdir01",
    //     "./test-ltp.sh ltp/testcases/bin/fchdir02",
    //     "./test-ltp.sh ltp/testcases/bin/fchdir03",
    //     "./test-ltp.sh ltp/testcases/bin/chmod01",
    //     "./test-ltp.sh ltp/testcases/bin/chmod03",
    //     "./test-ltp.sh ltp/testcases/bin/chmod05",
    //     "./test-ltp.sh ltp/testcases/bin/chmod06",
    //     "./test-ltp.sh ltp/testcases/bin/chmod07",
    //     "./test-ltp.sh ltp/testcases/bin/fchmod01",
    //     "./test-ltp.sh ltp/testcases/bin/fchmod02",
    // "./test-ltp.sh ltp/testcases/bin/fcntl01",
    // "./test-ltp.sh ltp/testcases/bin/fcntl01_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl02",
    // "./test-ltp.sh ltp/testcases/bin/fcntl02_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl03",
    // "./test-ltp.sh ltp/testcases/bin/fcntl03_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl04",
    // "./test-ltp.sh ltp/testcases/bin/fcntl04_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl05",
    // "./test-ltp.sh ltp/testcases/bin/fcntl05_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl07",
    // "./test-ltp.sh ltp/testcases/bin/fcntl07_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl08",
    // "./test-ltp.sh ltp/testcases/bin/fcntl08_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl09",
    // "./test-ltp.sh ltp/testcases/bin/fcntl09_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl10",
    // "./test-ltp.sh ltp/testcases/bin/fcntl10_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl11",
    // "./test-ltp.sh ltp/testcases/bin/fcntl11_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl12",
    // "./test-ltp.sh ltp/testcases/bin/fcntl12_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl13",
    // "./test-ltp.sh ltp/testcases/bin/fcntl13_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl14",
    // "./test-ltp.sh ltp/testcases/bin/fcntl14_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl15",
    // "./test-ltp.sh ltp/testcases/bin/fcntl15_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl16",
    // "./test-ltp.sh ltp/testcases/bin/fcntl16_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl17",
    // "./test-ltp.sh ltp/testcases/bin/fcntl17_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl18",
    // "./test-ltp.sh ltp/testcases/bin/fcntl18_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl19",
    // "./test-ltp.sh ltp/testcases/bin/fcntl19_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl20",
    // "./test-ltp.sh ltp/testcases/bin/fcntl20_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl21",
    // "./test-ltp.sh ltp/testcases/bin/fcntl21_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl22",
    // "./test-ltp.sh ltp/testcases/bin/fcntl22_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl23",
    // "./test-ltp.sh ltp/testcases/bin/fcntl23_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl24",
    // "./test-ltp.sh ltp/testcases/bin/fcntl24_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl25",
    // "./test-ltp.sh ltp/testcases/bin/fcntl25_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl26",
    // "./test-ltp.sh ltp/testcases/bin/fcntl26_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl27",
    // "./test-ltp.sh ltp/testcases/bin/fcntl27_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl29",
    // "./test-ltp.sh ltp/testcases/bin/fcntl29_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl30",
    // "./test-ltp.sh ltp/testcases/bin/fcntl30_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl31",
    // "./test-ltp.sh ltp/testcases/bin/fcntl31_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl32",
    // "./test-ltp.sh ltp/testcases/bin/fcntl32_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl33",
    // "./test-ltp.sh ltp/testcases/bin/fcntl33_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl34",
    // "./test-ltp.sh ltp/testcases/bin/fcntl34_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl35",
    // "./test-ltp.sh ltp/testcases/bin/fcntl35_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl36",
    // "./test-ltp.sh ltp/testcases/bin/fcntl36_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl37",
    // "./test-ltp.sh ltp/testcases/bin/fcntl37_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl38",
    // "./test-ltp.sh ltp/testcases/bin/fcntl38_64",
    // "./test-ltp.sh ltp/testcases/bin/fcntl39",
    // "./test-ltp.sh ltp/testcases/bin/fcntl39_64",
    //     "./test-ltp.sh ltp/testcases/bin/fsopen01",
    // "./test-ltp.sh ltp/testcases/bin/fsopen02",
    // "./test-ltp.sh ltp/testcases/bin/fspick01",
    // "./test-ltp.sh ltp/testcases/bin/fspick02",
    // "./test-ltp.sh ltp/testcases/bin/fstat02",
    // "./test-ltp.sh ltp/testcases/bin/fstat02_64",
    // "./test-ltp.sh ltp/testcases/bin/fstat03",
    // "./test-ltp.sh ltp/testcases/bin/fstat03_64",
    // "./test-ltp.sh ltp/testcases/bin/fstatat01",
    // "./test-ltp.sh ltp/testcases/bin/fstatfs01",
    // "./test-ltp.sh ltp/testcases/bin/fstatfs01_64",
    // "./test-ltp.sh ltp/testcases/bin/fstatfs02",
    // "./test-ltp.sh ltp/testcases/bin/fstatfs02_64",
    //     "./test-ltp.sh ltp/testcases/bin/getdomainname01",
    //     "./test-ltp.sh ltp/testcases/bin/fork01",
    //     "./test-ltp.sh ltp/testcases/bin/fork03",
    //     "./test-ltp.sh ltp/testcases/bin/fork04",
    //     "./test-ltp.sh ltp/testcases/bin/fork05",
    //     "./test-ltp.sh ltp/testcases/bin/fsopen01",
    //     "./test-ltp.sh ltp/testcases/bin/fsopen02",
    //     "./test-ltp.sh ltp/testcases/bin/fsmount01",
    //     "./test-ltp.sh ltp/testcases/bin/fsmount02",
    // "./test-ltp.sh ltp/testcases/bin/fsync01",
    // "./test-ltp.sh ltp/testcases/bin/fsync02",
    // "./test-ltp.sh ltp/testcases/bin/fsync03",
    // "./test-ltp.sh ltp/testcases/bin/fsync04",
    // "./test-ltp.sh ltp/testcases/bin/ftruncate01",
    // "./test-ltp.sh ltp/testcases/bin/ftruncate01_64",
    // "./test-ltp.sh ltp/testcases/bin/ftruncate03",
    // "./test-ltp.sh ltp/testcases/bin/ftruncate03_64",
    // "./test-ltp.sh ltp/testcases/bin/ftruncate04",
    // "./test-ltp.sh ltp/testcases/bin/ftruncate04_64",
    // "./test-ltp.sh ltp/testcases/bin/futimesat01",
    // "./test-ltp.sh ltp/testcases/bin/getcontext01",
    // "./test-ltp.sh ltp/testcases/bin/getcpu01",
    // "./test-ltp.sh ltp/testcases/bin/getcwd01",
    // "./test-ltp.sh ltp/testcases/bin/getcwd02",
    // "./test-ltp.sh ltp/testcases/bin/getcwd03",
    // "./test-ltp.sh ltp/testcases/bin/getcwd04",
    //     "./test-ltp.sh ltp/testcases/bin/getgid01",
    //     "./test-ltp.sh ltp/testcases/bin/getitimer01",
    //     "./test-ltp.sh ltp/testcases/bin/getitimer02",
    //     "./test-ltp.sh ltp/testcases/bin/getpeername01",
    //     "./test-ltp.sh ltp/testcases/bin/getpgid01",
    //     "./test-ltp.sh ltp/testcases/bin/getpid01",
    //     "./test-ltp.sh ltp/testcases/bin/getpid02",
    //     "./test-ltp.sh ltp/testcases/bin/getsockname01",
    //     "./test-ltp.sh ltp/testcases/bin/getsockopt01",
    //     "./test-ltp.sh ltp/testcases/bin/getsockopt02",
    //     "./test-ltp.sh ltp/testcases/bin/ioctl01",
    //     "./test-ltp.sh ltp/testcases/bin/ioctl02",
    //     "./test-ltp.sh ltp/testcases/bin/ioctl03",
    //     "./test-ltp.sh ltp/testcases/bin/ioctl04",
    //     "./test-ltp.sh ltp/testcases/bin/ioctl05",
    //     "./test-ltp.sh ltp/testcases/bin/kill02",
    //     "./test-ltp.sh ltp/testcases/bin/kill03",
    //     "./test-ltp.sh ltp/testcases/bin/kill05",
    //     "./test-ltp.sh ltp/testcases/bin/kill06",
    //     "./test-ltp.sh ltp/testcases/bin/kill07",
    //     "./test-ltp.sh ltp/testcases/bin/kill08",
    //     "./test-ltp.sh ltp/testcases/bin/lseek01",
    //     "./test-ltp.sh ltp/testcases/bin/lseek02",
    //     "./test-ltp.sh ltp/testcases/bin/mbind01",
    //     "./test-ltp.sh ltp/testcases/bin/mbind02",
    //     "./test-ltp.sh ltp/testcases/bin/mkdir02",
    //     "./test-ltp.sh ltp/testcases/bin/mkdir03",
    //     "./test-ltp.sh ltp/testcases/bin/mkdirat01",
    //     "./test-ltp.sh ltp/testcases/bin/mkdirat02",
    //     "./test-ltp.sh ltp/testcases/bin/mknod01",
    //     "./test-ltp.sh ltp/testcases/bin/mmap01",
    //     "./test-ltp.sh ltp/testcases/bin/mmap02",
    //     "./test-ltp.sh ltp/testcases/bin/mmap03",
    //     "./test-ltp.sh ltp/testcases/bin/mmap04",
    //     "./test-ltp.sh ltp/testcases/bin/mmap05",
    //     "./test-ltp.sh ltp/testcases/bin/abs01",
    //     "./test-ltp.sh ltp/testcases/bin/read01",
    //     "./test-ltp.sh ltp/testcases/bin/read02",
    //     "./test-ltp.sh ltp/testcases/bin/read03",
    //     "./test-ltp.sh ltp/testcases/bin/read04",
    //     "./test-ltp.sh ltp/testcases/bin/readv01",
    //     "./test-ltp.sh ltp/testcases/bin/readv02",
    //     "./test-ltp.sh ltp/testcases/bin/mount01",
    //     "./test-ltp.sh ltp/testcases/bin/mount02",
    //     "./test-ltp.sh ltp/testcases/bin/nanosleep01",
    //     "./test-ltp.sh ltp/testcases/bin/nanosleep02",
    //     "./test-ltp.sh ltp/testcases/bin/munmap01",
    //     "./test-ltp.sh ltp/testcases/bin/munmap02",
    //     "./test-ltp.sh ltp/testcases/bin/open01",
    //     "./test-ltp.sh ltp/testcases/bin/open02",
    //     "./test-ltp.sh ltp/testcases/bin/openat01",
    //     "./test-ltp.sh ltp/testcases/bin/openat02",
    //     "./test-ltp.sh ltp/testcases/bin/pipe01",
    //     "./test-ltp.sh ltp/testcases/bin/pipe02",
    //     "./test-ltp.sh ltp/testcases/bin/pipe03",
    //     "./test-ltp.sh ltp/testcases/bin/pipe04",
    //     "./test-ltp.sh ltp/testcases/bin/pipe05",
    //     "./test-ltp.sh ltp/testcases/bin/poll01",
    //     "./test-ltp.sh ltp/testcases/bin/poll02",
    //     "./test-ltp.sh ltp/testcases/bin/ppoll01",
    //     "./test-ltp.sh ltp/testcases/bin/pselect01",
    //     "./test-ltp.sh ltp/testcases/bin/pselect02",
    //     "./test-ltp.sh ltp/testcases/bin/readlinkat01",
    //     "./test-ltp.sh ltp/testcases/bin/readlinkat02",
    //     "./test-ltp.sh ltp/testcases/bin/rename01",
    //     "./test-ltp.sh ltp/testcases/bin/rt_sigaction01",
    //     "./test-ltp.sh ltp/testcases/bin/rt_sigaction02",
    //     "./test-ltp.sh ltp/testcases/bin/rt_sigaction03",
    //     "./test-ltp.sh ltp/testcases/bin/rt_sigprocmask01",
    //     "./test-ltp.sh ltp/testcases/bin/rt_sigprocmask02",
    //     "./test-ltp.sh ltp/testcases/bin/sched_yield01",
    //     "./test-ltp.sh ltp/testcases/bin/sendto01",
    //     "./test-ltp.sh ltp/testcases/bin/sendto02",
    //     "./test-ltp.sh ltp/testcases/bin/sendto03",
    //     "./test-ltp.sh ltp/testcases/bin/recvfrom01",
    //     "./test-ltp.sh ltp/testcases/bin/recv01",
    //     "./test-ltp.sh ltp/testcases/bin/setitimer01",
    //     "./test-ltp.sh ltp/testcases/bin/setitimer02",
    //     "./test-ltp.sh ltp/testcases/bin/setsockopt01",
    //     "./test-ltp.sh ltp/testcases/bin/setsockopt02",
    //     "./test-ltp.sh ltp/testcases/bin/setsockopt03",
    //     "./test-ltp.sh ltp/testcases/bin/setsockopt04",
    //     "./test-ltp.sh ltp/testcases/bin/setsockopt05",
    //     "./test-ltp.sh ltp/testcases/bin/setsockopt06",
    //     "./test-ltp.sh ltp/testcases/bin/setsockopt07",
    //     "./test-ltp.sh ltp/testcases/bin/setsockopt08",
    //     "./test-ltp.sh ltp/testcases/bin/setsockopt09",
    //     "./test-ltp.sh ltp/testcases/bin/setsockopt10",
    //     "./test-ltp.sh ltp/testcases/bin/sched_setparam01",
    //     "./test-ltp.sh ltp/testcases/bin/sched_setparam02",
    //     "./test-ltp.sh ltp/testcases/bin/sched_getscheduler01",
    //     "./test-ltp.sh ltp/testcases/bin/sched_getscheduler02",
    //     "./test-ltp.sh ltp/testcases/bin/socket01",
    //     "./test-ltp.sh ltp/testcases/bin/socket02",
    //     "./test-ltp.sh ltp/testcases/bin/stat01",
    //     "./test-ltp.sh ltp/testcases/bin/stat02",
    //     "./test-ltp.sh ltp/testcases/bin/time01",
    //     "./test-ltp.sh ltp/testcases/bin/times01",
    //     "./test-ltp.sh ltp/testcases/bin/times03",
    //     "./test-ltp.sh ltp/testcases/bin/utime01",
    //     "./test-ltp.sh ltp/testcases/bin/utime02",
    //     "./test-ltp.sh ltp/testcases/bin/utime03",
    //     "./test-ltp.sh ltp/testcases/bin/utime04",
    //     "./test-ltp.sh ltp/testcases/bin/utime05",
    //     "./test-ltp.sh ltp/testcases/bin/utime06",
    //     "./test-ltp.sh ltp/testcases/bin/waitpid01",
    //     "./test-ltp.sh ltp/testcases/bin/waitpid03",
    //     "./test-ltp.sh ltp/testcases/bin/waitpid04",
    //     "./test-ltp.sh ltp/testcases/bin/waitpid06",
    //     "./test-ltp.sh ltp/testcases/bin/write01",
    //     "./test-ltp.sh ltp/testcases/bin/write02",
    //     "./test-ltp.sh ltp/testcases/bin/write03",
    //     "./test-ltp.sh ltp/testcases/bin/write04",
    //     "./test-ltp.sh ltp/testcases/bin/write05",
    //     "./test-ltp.sh ltp/testcases/bin/write06",
    //     "./test-ltp.sh ltp/testcases/bin/writev01",
    //     "./test-ltp.sh ltp/testcases/bin/writev02",
    //     "./test-ltp.sh ltp/testcases/bin/writev03",
    //     "./test-ltp.sh ltp/testcases/bin/writev05",
    //     "./test-ltp.sh ltp/testcases/bin/writev06",
    //     "./test-ltp.sh ltp/testcases/bin/writev07",
    //     //
    //     "./test-ltp.sh ltp/testcases/bin/atof01",
    //     "./test-ltp.sh ltp/testcases/bin/float_bessel",
    //     "./test-ltp.sh ltp/testcases/bin/float_exp_log",
    //     "./test-ltp.sh ltp/testcases/bin/float_iperb",
    //     "./test-ltp.sh ltp/testcases/bin/float_power",
    //     "./test-ltp.sh ltp/testcases/bin/float_trigo",
    //     ///////
    //     "./test-ltp.sh ltp/testcases/bin/fptest01",
    //     "./test-ltp.sh ltp/testcases/bin/fptest02",
    //     "./test-ltp.sh ltp/testcases/bin/nextafter01",
    //     "./test-ltp.sh ltp/testcases/bin/squashfs01 ",
    //     //////
    //     "./test-ltp.sh ltp/testcases/bin/page01",
    //     "./test-ltp.sh ltp/testcases/bin/page02 ",
    //     "./test-ltp.sh ltp/testcases/bin/shmt02",
    //     "./test-ltp.sh ltp/testcases/bin/shmt03",
    //     "./test-ltp.sh ltp/testcases/bin/shmt04",
    //     "./test-ltp.sh ltp/testcases/bin/shmt05",
    //     "./test-ltp.sh ltp/testcases/bin/shmt06",
    //     "./test-ltp.sh ltp/testcases/bin/shmt07",
    //     "./test-ltp.sh ltp/testcases/bin/shmt08",
    //     "./test-ltp.sh ltp/testcases/bin/shmt09",
    //     "./test-ltp.sh ltp/testcases/bin/shmt10",
    //     ///////
    //     "./test-ltp.sh ltp/testcases/bin/mmapstress01",
    //     "./test-ltp.sh ltp/testcases/bin/mmapstress02",
    //     "./test-ltp.sh ltp/testcases/bin/mmapstress03",
    //     "./test-ltp.sh ltp/testcases/bin/mmapstress04",
    //     "./test-ltp.sh ltp/testcases/bin/mmapstress05",
    //     "./test-ltp.sh ltp/testcases/bin/mmapstress06",
    //     "./test-ltp.sh ltp/testcases/bin/mmapstress07",
    //     "./test-ltp.sh ltp/testcases/bin/mmapstress08",
    //     "./test-ltp.sh ltp/testcases/bin/mmapstress09",
    //     "./test-ltp.sh ltp/testcases/bin/mmapstress10",
    //     ////
    //     "./test-ltp.sh ltp/testcases/bin/kallsyms",
    //     "./test-ltp.sh ltp/testcases/bin/ksm01",
    //     "./test-ltp.sh ltp/testcases/bin/ksm02",
    //     "./test-ltp.sh ltp/testcases/bin/ksm03",
    //     "./test-ltp.sh ltp/testcases/bin/ksm04",
    //     "./test-ltp.sh ltp/testcases/bin/ksm05",
    //     "./test-ltp.sh ltp/testcases/bin/ksm06",
    //     "./test-ltp.sh ltp/testcases/bin/ksm07",
    //     "./test-ltp.sh ltp/testcases/bin/cpuset01",
    //     ///
    //     "./test-ltp.sh ltp/testcases/bin/oom01",
    //     "./test-ltp.sh ltp/testcases/bin/oom02",
    //     "./test-ltp.sh ltp/testcases/bin/oom03",
    //     "./test-ltp.sh ltp/testcases/bin/oom04",
    //     "./test-ltp.sh ltp/testcases/bin/oom05",
    //     ////
    //     "./test-ltp.sh ltp/testcases/bin/thp01",
    //     "./test-ltp.sh ltp/testcases/bin/thp02",
    //     "./test-ltp.sh ltp/testcases/bin/thp03",
    //     "./test-ltp.sh ltp/testcases/bin/thp04",
    //     ////
    //     "./test-ltp.sh ltp/testcases/bin/vma01",
    //     "./test-ltp.sh ltp/testcases/bin/vma02",
    //     "./test-ltp.sh ltp/testcases/bin/vma03",
    //     "./test-ltp.sh ltp/testcases/bin/vma04",
    //     "./test-ltp.sh ltp/testcases/bin/input01",
    //     "./test-ltp.sh ltp/testcases/bin/input02",
    //     "./test-ltp.sh ltp/testcases/bin/input03",
    //     "./test-ltp.sh ltp/testcases/bin/input04",
    //     "./test-ltp.sh ltp/testcases/bin/input05",
    //     "./test-ltp.sh ltp/testcases/bin/input06",
    //     ////
    //     "./test-ltp.sh ltp/testcases/bin/hugefallocate01",
    //     "./test-ltp.sh ltp/testcases/bin/hugefallocate02",
    //     "./test-ltp.sh ltp/testcases/bin/hugefork01",
    //     "./test-ltp.sh ltp/testcases/bin/hugefork02",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap01",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap02",
    //     ////
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmat01",
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmat02",
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmat03",
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmat04",
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmat05",
    //     ////
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmctl01",
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmctl02",
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmctl03",
    //     ////
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmdt01",
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmget01",
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmget02",
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmget03",
    //     "./test-ltp.sh ltp/testcases/bin/hugeshmget05",
    //     "./test-ltp.sh ltp/testcases/bin/pty01",
    //     "./test-ltp.sh ltp/testcases/bin/pty02",
    //     "./test-ltp.sh ltp/testcases/bin/pty03",
    //     "./test-ltp.sh ltp/testcases/bin/pty04",
    //     "./test-ltp.sh ltp/testcases/bin/pty05",
    //     "./test-ltp.sh ltp/testcases/bin/pty06",
    //     "./test-ltp.sh ltp/testcases/bin/pty07",
    //     "./test-ltp.sh ltp/testcases/bin/ptem01",
    //     "./test-ltp.sh ltp/testcases/bin/hangup01",
    //     "./test-ltp.sh ltp/testcases/bin/nptl01",
    //     ////
    //     "./test-ltp.sh ltp/testcases/bin/move_pages01",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages02",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages03",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages04",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages05",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages06",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages07",
    //     "./test-ltp.sh ltp/testcases/bin/set_mempolicy01",
    //     "./test-ltp.sh ltp/testcases/bin/set_mempolicy02",
    //     "./test-ltp.sh ltp/testcases/bin/set_mempolicy03",
    //     "./test-ltp.sh ltp/testcases/bin/set_mempolicy04",
    //     "./test-ltp.sh ltp/testcases/bin/set_mempolicy05",
    //     "./test-ltp.sh ltp/testcases/bin/syslog11",
    //     "./test-ltp.sh ltp/testcases/bin/syslog12",
    //     /////
    //     "./test-ltp.sh ltp/testcases/bin/pth_str01",
    //     "./test-ltp.sh ltp/testcases/bin/pth_str02",
    //     "./test-ltp.sh ltp/testcases/bin/pth_str03",
    //     /////
    //     "./test-ltp.sh ltp/testcases/bin/cfs_bandwidth01",
    //     "./test-ltp.sh ltp/testcases/bin/starvation",
    //     "./test-ltp.sh ltp/testcases/bin/proc_sched_rt01",
    //     "./test-ltp.sh ltp/testcases/bin/autogroup01",
    //     ////
    //     "./test-ltp.sh ltp/testcases/bin/cve-2014-0196",
    //     "./test-ltp.sh ltp/testcases/bin/cve-2015-3290",
    //     "./test-ltp.sh ltp/testcases/bin/cve-2016-7042",
    //     "./test-ltp.sh ltp/testcases/bin/cve-2016-7117 ",
    //     "./test-ltp.sh ltp/testcases/bin/cve-2017-2618",
    //     "./test-ltp.sh ltp/testcases/bin/cve-2017-2671",
    //     "./test-ltp.sh ltp/testcases/bin/cve-2017-16939",
    //     "./test-ltp.sh ltp/testcases/bin/cve-2017-17052 ",
    //     "./test-ltp.sh ltp/testcases/bin/cve-2017-17053",
    //     "./test-ltp.sh ltp/testcases/bin/cve-2022-4378",
    //     "./test-ltp.sh ltp/testcases/bin/open03",
    //     "./test-ltp.sh ltp/testcases/bin/open04",
    //     "./test-ltp.sh ltp/testcases/bin/open06",
    //     "./test-ltp.sh ltp/testcases/bin/open07",
    //     "./test-ltp.sh ltp/testcases/bin/msgctl01",
    //     "./test-ltp.sh ltp/testcases/bin/msgctl02",
    //     "./test-ltp.sh ltp/testcases/bin/msgctl03",
    //     "./test-ltp.sh ltp/testcases/bin/msgctl04",
    //     "./test-ltp.sh ltp/testcases/bin/msgctl05",
    //     "./test-ltp.sh ltp/testcases/bin/msgctl06",
    //     "./test-ltp.sh ltp/testcases/bin/msgctl12",
    //     //
    //     "./test-ltp.sh ltp/testcases/bin/msgstress01",
    //     //
    //     "./test-ltp.sh ltp/testcases/bin/msgget01",
    //     "./test-ltp.sh ltp/testcases/bin/msgget02",
    //     "./test-ltp.sh ltp/testcases/bin/msgget03",
    //     "./test-ltp.sh ltp/testcases/bin/msgget04",
    //     "./test-ltp.sh ltp/testcases/bin/msgget05",
    //     ///
    //     "./test-ltp.sh ltp/testcases/bin/msgrcv01",
    //     "./test-ltp.sh ltp/testcases/bin/msgrcv02",
    //     "./test-ltp.sh ltp/testcases/bin/msgrcv03",
    //     "./test-ltp.sh ltp/testcases/bin/msgrcv05",
    //     "./test-ltp.sh ltp/testcases/bin/msgrcv06",
    //     "./test-ltp.sh ltp/testcases/bin/msgrcv07",
    //     "./test-ltp.sh ltp/testcases/bin/msgrcv08",
    //     //
    //     "./test-ltp.sh ltp/testcases/bin/msgsnd01",
    //     "./test-ltp.sh ltp/testcases/bin/msgsnd02",
    //     "./test-ltp.sh ltp/testcases/bin/msgsnd05",
    //     "./test-ltp.sh ltp/testcases/bin/msgsnd06",
    //     //
    //     "./test-ltp.sh ltp/testcases/bin/semctl01",
    //     "./test-ltp.sh ltp/testcases/bin/semctl02",
    //     "./test-ltp.sh ltp/testcases/bin/semctl03",
    //     "./test-ltp.sh ltp/testcases/bin/semctl04",
    //     "./test-ltp.sh ltp/testcases/bin/semctl05",
    //     "./test-ltp.sh ltp/testcases/bin/semctl06",
    //     "./test-ltp.sh ltp/testcases/bin/semctl07",
    //     "./test-ltp.sh ltp/testcases/bin/semctl08",
    //     "./test-ltp.sh ltp/testcases/bin/semctl09",
    //     //
    //     "./test-ltp.sh ltp/testcases/bin/semget01",
    //     "./test-ltp.sh ltp/testcases/bin/semget02",
    //     "./test-ltp.sh ltp/testcases/bin/semget05",
    //     //
    //     "./test-ltp.sh ltp/testcases/bin/semop01",
    //     "./test-ltp.sh ltp/testcases/bin/semop02",
    //     "./test-ltp.sh ltp/testcases/bin/semop03",
    //     //
    //     "./test-ltp.sh ltp/testcases/bin/shmat01",
    //     "./test-ltp.sh ltp/testcases/bin/shmat02",
    //     "./test-ltp.sh ltp/testcases/bin/shmat04",
    //     //
    //     "./test-ltp.sh ltp/testcases/bin/shmctl01",
    //     "./test-ltp.sh ltp/testcases/bin/shmctl02",
    //     "./test-ltp.sh ltp/testcases/bin/shmctl03",
    //     "./test-ltp.sh ltp/testcases/bin/shmctl04",
    //     "./test-ltp.sh ltp/testcases/bin/shmctl05",
    //     "./test-ltp.sh ltp/testcases/bin/shmctl06",
    //     "./test-ltp.sh ltp/testcases/bin/shmctl07",
    //     "./test-ltp.sh ltp/testcases/bin/shmctl08",
    //     //
    //     "./test-ltp.sh ltp/testcases/bin/shmdt01",
    //     "./test-ltp.sh ltp/testcases/bin/shmdt02",
    //     //
    //     "./test-ltp.sh ltp/testcases/bin/shmget02",
    //     "./test-ltp.sh ltp/testcases/bin/shmget03",
    //     "./test-ltp.sh ltp/testcases/bin/shmget04",
    //     "./test-ltp.sh ltp/testcases/bin/shmget05",
    //     "./test-ltp.sh ltp/testcases/bin/shmget06",
    //     //
    //     "./test-ltp.sh ltp/testcases/bin/can_rcv_own_msgs",
    //     "./test-ltp.sh ltp/testcases/bin/can_bcm01",
    //     "./test-ltp.sh ltp/testcases/bin/can_filter",

    //     "./test-ltp.sh ltp/testcases/bin/check_keepcaps 1",
    //     "./test-ltp.sh ltp/testcases/bin/check_keepcaps 2",
    //     "./test-ltp.sh ltp/testcases/bin/check_keepcaps 3",

    // "./test-ltp.sh ltp/testcases/bin/can_rcv_own_msgs",
    //     "./test-ltp.sh ltp/testcases/bin/can_bcm01",
    //     "./test-ltp.sh ltp/testcases/bin/can_filter",
    //     "./test-ltp.sh ltp/testcases/bin/check_keepcaps 1",
    //     "./test-ltp.sh ltp/testcases/bin/check_keepcaps 2",
    //     "./test-ltp.sh ltp/testcases/bin/check_keepcaps 3",
    //     "./test-ltp.sh ltp/testcases/bin/pidns01",
    //     "./test-ltp.sh ltp/testcases/bin/pidns02",
    //     "./test-ltp.sh ltp/testcases/bin/pidns03",
    //     "./test-ltp.sh ltp/testcases/bin/pidns04",
    //     "./test-ltp.sh ltp/testcases/bin/pidns05",
    //     "./test-ltp.sh ltp/testcases/bin/pidns06",
    //     "./test-ltp.sh ltp/testcases/bin/pidns10",
    //     "./test-ltp.sh ltp/testcases/bin/pidns12",
    //     "./test-ltp.sh ltp/testcases/bin/pidns13",
    //     "./test-ltp.sh ltp/testcases/bin/pidns16",
    //     "./test-ltp.sh ltp/testcases/bin/pidns17",
    //     "./test-ltp.sh ltp/testcases/bin/pidns20",
    //     "./test-ltp.sh ltp/testcases/bin/pidns30",
    //     "./test-ltp.sh ltp/testcases/bin/pidns31",
    //     "./test-ltp.sh ltp/testcases/bin/pidns32",
    //     "./test-ltp.sh ltp/testcases/bin/mqns_01",
    //     "./test-ltp.sh ltp/testcases/bin/netns_netlink",
    //     "./test-ltp.sh ltp/testcases/bin/userns01",
    //     "./test-ltp.sh ltp/testcases/bin/userns02",
    //     "./test-ltp.sh ltp/testcases/bin/userns03",
    //     "./test-ltp.sh ltp/testcases/bin/userns04",
    //     "./test-ltp.sh ltp/testcases/bin/userns05",
    //     "./test-ltp.sh ltp/testcases/bin/userns06",
    //     "./test-ltp.sh ltp/testcases/bin/userns07",
    //     "./test-ltp.sh ltp/testcases/bin/userns08",
    //     "./test-ltp.sh ltp/testcases/bin/mountns01",
    //     "./test-ltp.sh ltp/testcases/bin/mountns02",
    //     "./test-ltp.sh ltp/testcases/bin/mountns03",
    //     "./test-ltp.sh ltp/testcases/bin/mountns04",
    //     "./test-ltp.sh ltp/testcases/bin/sysinfo03",
    //     "./test-ltp.sh ltp/testcases/bin/timens01",
    //     "./test-ltp.sh ltp/testcases/bin/timerfd04",
    //     "./test-ltp.sh ltp/testcases/bin/memcontrol01",
    //     "./test-ltp.sh ltp/testcases/bin/memcontrol02",
    //     "./test-ltp.sh ltp/testcases/bin/memcontrol03",
    //     "./test-ltp.sh ltp/testcases/bin/memcontrol04",
    //     "./test-ltp.sh ltp/testcases/bin/cgroup_core01",
    //     "./test-ltp.sh ltp/testcases/bin/cgroup_core02",
    //     "./test-ltp.sh ltp/testcases/bin/cgroup_core03",
    //     "./test-ltp.sh ltp/testcases/bin/af_alg01",
    //     "./test-ltp.sh ltp/testcases/bin/af_alg02",
    //     "./test-ltp.sh ltp/testcases/bin/af_alg03",
    //     "./test-ltp.sh ltp/testcases/bin/af_alg04",
    //     "./test-ltp.sh ltp/testcases/bin/af_alg05",
    //     "./test-ltp.sh ltp/testcases/bin/af_alg06",
    //     "./test-ltp.sh ltp/testcases/bin/af_alg07",
    //     "./test-ltp.sh ltp/testcases/bin/pcrypt_aead01",
    //     "./test-ltp.sh ltp/testcases/bin/crypto_user01",
    //     "./test-ltp.sh ltp/testcases/bin/crypto_user02",
    //     "./test-ltp.sh ltp/testcases/bin/inode01",
    //     "./test-ltp.sh ltp/testcases/bin/inode02",
    //     "./test-ltp.sh ltp/testcases/bin/stream01",
    //     "./test-ltp.sh ltp/testcases/bin/stream02",
    //     "./test-ltp.sh ltp/testcases/bin/stream03",
    //     "./test-ltp.sh ltp/testcases/bin/stream04",
    //     "./test-ltp.sh ltp/testcases/bin/stream05",
    //     "./test-ltp.sh ltp/testcases/bin/ftest01",
    //     "./test-ltp.sh ltp/testcases/bin/ftest02",
    //     "./test-ltp.sh ltp/testcases/bin/ftest03",
    //     "./test-ltp.sh ltp/testcases/bin/ftest04",
    //     "./test-ltp.sh ltp/testcases/bin/ftest05",
    //     "./test-ltp.sh ltp/testcases/bin/ftest06",
    //     "./test-ltp.sh ltp/testcases/bin/ftest07",
    //     "./test-ltp.sh ltp/testcases/bin/ftest08",

    //     "./test-ltp.sh ltp/testcases/bin/hugemmap01",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap02",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap04",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap05",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap06",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap07",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap08",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap09",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap10",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap11",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap12",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap13",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap14",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap15",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap16",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap17",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap18",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap19",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap20",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap21",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap22",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap23",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap24",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap25",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap26",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap27",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap28",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap29",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap30",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap31",
    //     "./test-ltp.sh ltp/testcases/bin/hugemmap32",
    //     "./test-ltp.sh ltp/testcases/bin/irqbalance01",

    //     "./test-ltp.sh ltp/testcases/bin/kmsg01",
    //     "./test-ltp.sh ltp/testcases/bin/fw_load",
    //     "./test-ltp.sh ltp/testcases/bin/rtc01",
    //     "./test-ltp.sh ltp/testcases/bin/rtc02",
    //     "./test-ltp.sh ltp/testcases/bin/block_dev",
    //     "./test-ltp.sh ltp/testcases/bin/tpci",
    //     "./test-ltp.sh ltp/testcases/bin/tbio",
    //     "./test-ltp.sh ltp/testcases/bin/ltp_acpi",
    //     "./test-ltp.sh ltp/testcases/bin/cpufreq_boost",
    //     "./test-ltp.sh ltp/testcases/bin/uaccess",
    //     "./test-ltp.sh ltp/testcases/bin/zram03",
    //     "./test-ltp.sh ltp/testcases/bin/umip_basic_test",
    //     "./test-ltp.sh ltp/testcases/bin/aslr01",
    //     "./test-ltp.sh ltp/testcases/bin/in6_01",
    //     "./test-ltp.sh ltp/testcases/bin/in6_02",
    //     "./test-ltp.sh ltp/testcases/bin/getaddrinfo_01",
    //     "./test-ltp.sh ltp/testcases/bin/asapi_01",
    //     "./test-ltp.sh ltp/testcases/bin/asapi_02",
    //     "./test-ltp.sh ltp/testcases/bin/asapi_03",

    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_accept_close",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_addrs",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_connect",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_connectx",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_events",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_initmsg_connect",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_nonblock",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_recvfrom",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_recvmsg",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_rtoinfo",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_send",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_sendmsg",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_sendto",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_shutdown",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_socket_bind_listen",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_sockopt",
    //     "./test-ltp.sh ltp/testcases/bin/test_1_to_1_threads",
    //     "./test-ltp.sh ltp/testcases/bin/test_assoc_abort",
    //     "./test-ltp.sh ltp/testcases/bin/test_assoc_shutdown",
    //     "./test-ltp.sh ltp/testcases/bin/test_autoclose",
    //     "./test-ltp.sh ltp/testcases/bin/test_basic",
    //     "./test-ltp.sh ltp/testcases/bin/test_basic_v6",
    //     "./test-ltp.sh ltp/testcases/bin/test_connect",
    //     "./test-ltp.sh ltp/testcases/bin/test_connectx",
    //     "./test-ltp.sh ltp/testcases/bin/test_fragments",
    //     "./test-ltp.sh ltp/testcases/bin/test_fragments_v6",
    //     "./test-ltp.sh ltp/testcases/bin/test_getname",
    //     "./test-ltp.sh ltp/testcases/bin/test_getname_v6",
    //     "./test-ltp.sh ltp/testcases/bin/test_inaddr_any",
    //     "./test-ltp.sh ltp/testcases/bin/test_inaddr_any_v6",
    //     "./test-ltp.sh ltp/testcases/bin/test_peeloff",
    //     "./test-ltp.sh ltp/testcases/bin/test_peeloff_v6",
    //     "./test-ltp.sh ltp/testcases/bin/test_recvmsg",
    //     "./test-ltp.sh ltp/testcases/bin/test_sctp_sendrecvmsg",
    //     "./test-ltp.sh ltp/testcases/bin/test_sctp_sendrecvmsg_v6",
    //     "./test-ltp.sh ltp/testcases/bin/test_sockopt",
    //     "./test-ltp.sh ltp/testcases/bin/test_sockopt_v6",
    //     "./test-ltp.sh ltp/testcases/bin/test_tcp_style",
    //     "./test-ltp.sh ltp/testcases/bin/test_tcp_style_v6",
    //     "./test-ltp.sh ltp/testcases/bin/test_timetolive",
    //     "./test-ltp.sh ltp/testcases/bin/test_timetolive_v6",

    //     "./test-ltp.sh ltp/testcases/bin/migrate_pages01",
    //     "./test-ltp.sh ltp/testcases/bin/migrate_pages02",
    //     "./test-ltp.sh ltp/testcases/bin/migrate_pages03",

    //     "./test-ltp.sh ltp/testcases/bin/move_pages01",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages02",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages03",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages04",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages05",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages06",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages07",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages09",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages10",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages11",
    //     "./test-ltp.sh ltp/testcases/bin/move_pages12",

    //     "./test-ltp.sh ltp/testcases/bin/access01",
    //     "./test-ltp.sh ltp/testcases/bin/wait02",
    //     "./test-ltp.sh ltp/testcases/bin/symlink01",
    //     "./test-ltp.sh ltp/testcases/bin/utime07",
    //     "./test-ltp.sh ltp/testcases/bin/uevent01",
    //     "./test-ltp.sh ltp/testcases/bin/uevent02",
    //     "./test-ltp.sh ltp/testcases/bin/uevent03",

    //     "./test-ltp.sh ltp/testcases/bin/wqueue01",
    //     "./test-ltp.sh ltp/testcases/bin/wqueue02",
    //     "./test-ltp.sh ltp/testcases/bin/wqueue03",
    //     "./test-ltp.sh ltp/testcases/bin/wqueue04",
    //     "./test-ltp.sh ltp/testcases/bin/wqueue05",
    //     "./test-ltp.sh ltp/testcases/bin/wqueue06",
    //     "./test-ltp.sh ltp/testcases/bin/wqueue07",
    //     "./test-ltp.sh ltp/testcases/bin/wqueue08",
    //     "./test-ltp.sh ltp/testcases/bin/wqueue09",
];

pub fn run_tests() {
    let commands = [
        "./time-test\0",
        "./libc-bench\0",
        "./run-static.sh\0",
        "./run-dynamic.sh\0",
        "./unixbench_testcode.sh\0",
        "./lmbench_testcode.sh\0",
        "./lua_testcode.sh\0",
        "./netperf_testcode.sh\0",
        "./iperf_testcode.sh\0",
        "./iozone_testcode.sh\0",
        "./cyclictest_testcode.sh\0",
        // "./interrupts-test-1\0",
        // "./interrupts-test-2\0",
        // "./busybox_testcode.sh\0",
        // "./copy-file-range-test-1\0",
        // "./copy-file-range-test-2\0",
        // "./copy-file-range-test-3\0",
        // "./copy-file-range-test-4\0",
    ];
    commands.into_iter().for_each(|app| {
        let args = [app.as_ptr(), core::ptr::null::<u8>()];
        let envp = [core::ptr::null::<u8>()];
        let pid = fork();
        if fork() == 0 {
            execve(app, &args, &envp);
            exit(0);
        } else {
            yield_();
            let mut exit_code: usize = 0;
            let _x = wait(pid as isize, &mut exit_code);
        }
    });
}

#[no_mangle]
fn main() -> i32 {
    if fork() == 0 {
        for testcase in TESTCASES {
            let pid = fork();
            if pid == 0 {
                if testcase.contains("./test-ltp.sh") {
                    let testname = "./test-ltp.sh".to_string() + "\0";
                    let prefix_to_remove = "./test-ltp.sh ";
                    let arg = testcase.strip_prefix(prefix_to_remove).unwrap().to_string() + "\0";
                    if execve(
                        &testname,
                        &[testname.as_ptr(), arg.as_ptr(), core::ptr::null::<u8>()],
                        &[core::ptr::null::<u8>()],
                    ) != 0
                    {
                        println!("Error when executing!");
                        return 0;
                    }
                } else {
                    let testname = testcase.to_string() + "\0";
                    if execve(
                        &testname,
                        &[testname.as_ptr(), core::ptr::null::<u8>()],
                        &[core::ptr::null::<u8>()],
                    ) != 0
                    {
                        println!("Error when executing!");
                        return 0;
                    }
                }
            } else {
                let mut exit_code: usize = 0;
                wait(pid, &mut exit_code);
            }
        }
        println!(" TEST FINISH! ");
        system_shutdown();
    } else {
        loop {
            let mut exit_code: usize = 0;
            let _pid = wait(-1, &mut exit_code);
        }
    }
    0
}

const BASH_ENV: &[*const u8] = &[
    "SHELL=/bash\0".as_ptr(),
    "PWD=/\0".as_ptr(),
    "LOGNAME=root\0".as_ptr(),
    "MOTD_SHOWN=pam\0".as_ptr(),
    "HOME=/root\0".as_ptr(),
    "LANG=C.UTF-8\0".as_ptr(),
    "TERM=vt220\0".as_ptr(),
    "USER=root\0".as_ptr(),
    "SHLVL=0\0".as_ptr(),
    "OLDPWD=/root\0".as_ptr(),
    "PS1=\x1b[1m\x1b[32mNoAxiom\x1b[0m:\x1b[1m\x1b[34m\\w\x1b[0m\\$ \0".as_ptr(),
    "_=/bin/bash\0".as_ptr(),
    "PATH=/:/bin\0".as_ptr(),
    "LD_LIBRARY_PATH=/\0".as_ptr(),
    core::ptr::null(),
];
