# workspace for kernel
[workspace]
members = ["libd", "apps/run_busybox", "apps/run_tests"]
resolver = "2"

[workspace.dependencies]
libd = { path = "./libd" }

[profile.release]
debug = true
opt-level = 3
overflow-checks = false
panic = "abort"
