[target.riscv64gc-unknown-none-elf]
linker = "rust-lld"
rustflags = ["-Clink-arg=-Tapps/linker-rv.ld", "-Cforce-frame-pointers=yes"]

[target.loongarch64-unknown-linux-gnu]
linker = "loongarch64-linux-gnu-gcc"
rustflags = [
    "-Clink-arg=-Tapps/linker-la.ld",
    "-Clink-arg=-nostdlib",
    "-Clink-arg=-static",
]

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
